/**
 * @summary Events sent from renderer process to main process
 */
export enum IPCRendererEnum {
  autoFitSearchWindowSize = '@ipcRenderer/autoFitSearchWindowSize',
  dispatchAction = '@ipcRenderer/dispatchAction',
  getSystemFont = '@ipcRenderer/getSystemFont',
  hideLargeTextWindow = '@ipcRenderer/hideLargeTextWindow',
  hideQuicklookWindow = '@ipcRenderer/hideQuicklookWindow',
  hideClipboardHistoryWindow = '@ipcRenderer/hideClipboardHistoryWindow',
  hideSearchWindow = '@ipcRenderer/hideSearchWindow',
  importTheme = '@ipcRenderer/importTheme',
  openPluginInstallFileDialog = '@ipcRenderer/openPluginInstallFileDialog',
  openWorkflowInstallFileDialog = '@ipcRenderer/openWorkflowInstallFileDialog',
  openYesnoDialog = '@ipcRenderer/openYesnoDialog',
  popupPluginItemMenu = '@ipcRenderer/popupPluginItemMenu',
  popupSearchbarItemMenu = '@ipcRenderer/popupSearchbarItemMenu',
  popupWorkflowItemMenu = '@ipcRenderer/popupWorkflowItemMenu',
  registerAllShortcuts = '@ipcRenderer/registerAllShortcuts',
  renewPlugin = '@ipcRenderer/renewPlugin',
  renewWorkflow = '@ipcRenderer/renewWorkflow',
  resizeSearchWindowHeight = '@ipcRenderer/resizeSearchWindowHeight',
  resumeFileWatch = '@ipcRenderer/resumeFileWatch',
  saveFile = '@ipcRenderer/saveFile',
  setAutoLaunch = '@ipcRenderer/setAutoLaunch',
  setGlobalShortcut = '@ipcRenderer/setGlobalShortcut',
  setSearchWindowWidth = '@ipcRenderer/setSearchWindowWidth',
  showErrorDialog = '@ipcRenderer/showErrorDialog',
  showLargeTextWindow = '@ipcRenderer/showLargeTextWindow',
  showNotification = '@ipcRenderer/showNotification',
  showQuicklookWindow = '@ipcRenderer/showQuicklookWindow',
  stopFileWatch = '@ipcRenderer/stopFileWatch',
  triggerDoubleModifierKey = '@ipcRenderer/triggerDoubleModifierKey',
  triggerKeyDownEvent = '@ipcRenderer/triggerKeyDownEvent',
  unregisterAllShortcuts = '@ipcRenderer/unregisterAllShortcuts',
}

/**
 * @summary Events sent from main process to renderer process
 */
export enum IPCMainEnum {
  autoFitSearchWindowSizeRet = '@ipcMain/autoFitSearchWindowSizeRet',
  executeAction = '@ipcMain/executeAction',
  fetchAction = '@ipcMain/fetchAction',
  forwardClipboardData = '@ipcMain/forwardClipboardData',
  forwardLargeText = '@ipcMain/forwardLargeText',
  forwardQuicklookWindowUrl = '@ipcMain/forwardQuicklookWindowUrl',
  getSystemFontRet = '@ipcMain/getSystemFontRet',
  hideSearchWindowByBlurEvent = '@ipcMain/hideSearchWindowByBlurEvent',
  importThemeRet = '@ipcMain/importThemeRet',
  openPluginInstallFileDialogRet = '@ipcMain/openPluginInstallFileDialogRet',
  openWorkflowInstallFileDialogRet = '@ipcMain/openWorkflowInstallFileDialogRet',
  openYesnoDialogRet = '@ipcMain/openYesnoDialogRet',
  pinSearchWindow = '@ipcMain/pinSearchWindow',
  registerAllShortcuts = '@ipcMain/registerAllShortcuts',
  renewClipboardStore = '@ipcMain/renewClipboardStore',
  renewPlugin = '@ipcMain/renewPlugin',
  renewWorkflow = '@ipcMain/renewWorkflow',
  saveFileRet = '@ipcMain/saveFileRet',
  searchWindowShowCallback = '@ipcMain/searchWindowShowCallback',
  setPreferencePage = '@ipcMain/setPreferencePage',
  setSearchbarInput = '@ipcMain/setSearchbarInput',
  togglePluginsEnabled = '@ipcMain/togglePluginsEnabled',
  toggleWorkflowsEnabled = '@ipcMain/toggleWorkflowsEnabled',
}
